# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.11
neo_version=21.11.37-beta
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
mod_group=com.mrbysco.sweaters
mod_id=sweaters
mod_archive_name=Sweaters

#Publishing
mod_name=Sweaters
curseforge_id=737472
modrinth_id=1Q1NmVPD

# Version
version=0.2.2

# Dependencies
jei_minecraft=1.21.11
jei_version=27.4.0.15
statues_version=0.4.8