modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Sweaters/issues"
license="MIT"

[[mods]]
modId="sweaters"
version="${file.jarVersion}"
displayName="Sweaters"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sweaters"
authors="Mrbysco, ShyNieke"
description='''
Deck out your mobs in ugly Christmas sweaters with the Sweaters mod!
'''
[[dependencies.sweaters]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.sweaters]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"